name: Extract DTB from boot.img

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  extract-dtb:

    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up environment
      run: sudo apt-get install -y abootimg curl

    - name: Download boot.img
      run: curl -L -o boot.img  https://sourceforge.net/projects/payload/files/Boot/boot.img # Replace with actual boot.img URL

    - name: Extract DTB
      run: |
        mkdir extracted
        abootimg --extract boot.img -o extracted/
        mv extracted/*.dtb extracted_dtb.dtb

    - name: Upload extracted DTB
      uses: actions/upload-artifact@v3  # Use version 3
      with:
        name: extracted-dtb-${{ github.run_id }}  # Unique name with run ID
        path: extracted_dtb.dtb
