name: Kernel Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      KERNEL_REPO: BlissRoms-Devices/android_kernel_asus_sm8250
      CLANG_REPO: SA9990/proton-clang
      KERNEL_DIR: android_kernel_asus_sm8250
      CLANG_DIR: proton-clang
      DEFCONFIG: vendor/obiwan_defconfig
      ARCH: arm64
      CROSS_COMPILE: aarch64-linux-gnu-
      CROSS_COMPILE_ARM32: arm-linux-gnueabi-

    steps:
      - name: Checkout Kernel Source
        uses: actions/checkout@v2
        with:
          repository: ${{ env.KERNEL_REPO }}
          path: ${{ env.KERNEL_DIR }}
          fetch-depth: 1

      - name: Checkout Proton Clang
        uses: actions/checkout@v2
        with:
          repository: ${{ env.CLANG_REPO }}
          path: ${{ env.CLANG_DIR }}
          fetch-depth: 1

      - name: Install Build Dependencies
        run: sudo apt-get update && sudo apt-get install -y bc bison flex libssl-dev make gcc

      - name: Set up Environment for Clang
        run: |
          export PATH="${{ env.CLANG_DIR }}/bin:$PATH"
          export LD=ld.lld
          export CC=clang
          export CROSS_COMPILE="${{ env.CLANG_DIR }}/bin/aarch64-linux-gnu-"
          export CROSS_COMPILE_ARM32="${{ env.CLANG_DIR }}/bin/arm-linux-gnueabi-"
          export CLANG_TRIPLE=aarch64-linux-gnu-

      - name: Build Kernel
        working-directory: ${{ env.KERNEL_DIR }}
        run: |
          make O=out ARCH=${{ env.ARCH }} ${{ env.DEFCONFIG }} 2>&1 | tee build.log
          make -j$(nproc) O=out ARCH=${{ env.ARCH }} \
          CC=clang \
          LD=ld.lld \
          CLANG_TRIPLE=${{ env.CROSS_COMPILE }} \
          CROSS_COMPILE=${{ env.CROSS_COMPILE }} \
          CROSS_COMPILE_ARM32=${{ env.CROSS_COMPILE_ARM32 }} 2>&1 | tee -a build.log

      - name: Upload Build Artifacts
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: Kernel
          path: ${{ env.KERNEL_DIR }}/out/arch/arm64/boot/Image.gz-dtb

      - name: Upload Build Log
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: Build Log
          path: ${{ env.KERNEL_DIR }}/build.log
