name: Extract Kernel from boot.img

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  extract-kernel:

    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up environment
      run: sudo apt-get install -y abootimg curl

    - name: Download boot.img
      run: |
        curl -L -o boot.img https://sourceforge.net/projects/payload/files/Boot/boot.img  # Ensure URL is correct

    - name: Extract Kernel
      run: |
        mkdir -p extracted
        abootimg --extract boot.img -o extracted/
        echo "Extracted files:"
        ls extracted/
        if [ -f extracted/zImage ]; then  # Change if kernel filename is different
          mv extracted/zImage extracted_kernel.img
        else
          echo "No kernel file found!"
          exit 1
        fi

    - name: Upload extracted Kernel
      uses: actions/upload-artifact@v3
      with:
        name: extracted-kernel-${{ github.run_id }}
        path: extracted_kernel.img
