name: Kernel Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      KERNEL_REPO: BlissRoms-Devices/android_kernel_asus_sm8250
      CLANG_REPO: SA9990/proton-clang
      KERNEL_DIR: android_kernel_asus_sm8250
      CLANG_DIR: proton-clang
      DEFCONFIG: vendor/obiwan_defconfig
      ARCH: arm64
      CROSS_COMPILE: aarch64-linux-gnu-
      CROSS_COMPILE_ARM32: arm-linux-gnueabi-

    steps:
      - name: Checkout Kernel Source
        uses: actions/checkout@v2
        with:
          repository: ${{ env.KERNEL_REPO }}
          path: ${{ env.KERNEL_DIR }}
          fetch-depth: 1

      - name: Checkout Proton Clang
        uses: actions/checkout@v2
        with:
          repository: ${{ env.CLANG_REPO }}
          path: ${{ env.CLANG_DIR }}
          fetch-depth: 1

      - name: Install Build Dependencies
        run: sudo apt-get update && sudo apt-get install -y bc bison flex libssl-dev make gcc clang lld

      - name: Build Kernel
        working-directory: ${{ env.KERNEL_DIR }}
        run: |
          # Set up environment for Clang and ensure it uses Clang's built-in tools
          export PATH="${{ env.CLANG_DIR }}/bin:$PATH"
          export ARCH=arm64
          export SUBARCH=arm64
          export LD=ld.lld
          export CC=clang
          export CLANG_TRIPLE=aarch64-linux-gnu-
          export CROSS_COMPILE="${{ env.CLANG_DIR }}/bin/aarch64-linux-gnu-"
          export CROSS_COMPILE_ARM32="${{ env.CLANG_DIR }}/bin/arm-linux-gnueabi-"
          
          # Configure the kernel
          make O=out ARCH=$ARCH CROSS_COMPILE=$CROSS_COMPILE CROSS_COMPILE_ARM32=$CROSS_COMPILE_ARM32 vendor/obiwan_defconfig 2>&1 | tee build.log

          # Build the kernel
          make -j$(nproc) O=out ARCH=$ARCH \
          CC=$CC \
          LD=$LD \
          CLANG_TRIPLE=$CLANG_TRIPLE \
          CROSS_COMPILE=$CROSS_COMPILE \
          CROSS_COMPILE_ARM32=$CROSS_COMPILE_ARM32 2>&1 | tee -a build.log

      - name: Upload Kernel Build Artifacts
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: Kernel
          path: ${{ env.KERNEL_DIR }}/out/arch/arm64/boot/Image.gz-dtb

      - name: Upload Build Log
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: Build Log
          path: ${{ env.KERNEL_DIR }}/build.log
