name: Build ASUS SM8250 Kernel

on:
  push:
    branches:
      - main
      - lineage-21
  pull_request:
    branches:
      - main
      - lineage-21

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            git \
            libncurses-dev \
            bison \
            flex \
            libssl-dev \
            libelf-dev \
            python3 \
            python3-pip \
            device-tree-compiler \
            clang \
            lld

      - name: Download and Set Up Toolchain
        run: |
          wget https://github.com/LineageOS/android_toolchain/releases/download/llvm-r16/llvm-toolchain-linux-aarch64-ubuntu-16.04.tar.gz -O toolchain.tar.gz
          mkdir -p $HOME/toolchain
          tar -xzf toolchain.tar.gz -C $HOME/toolchain --strip-components=1
          echo "export PATH=\$PATH:$HOME/toolchain/bin" >> $GITHUB_ENV
          echo "Toolchain setup completed."

      - name: Set Environment Variables
        run: |
          echo "ARCH=arm64" >> $GITHUB_ENV
          echo "CROSS_COMPILE=aarch64-linux-gnu-" >> $GITHUB_ENV

      - name: Configure Kernel
        run: |
          cd android_kernel_asus_sm8250
          git checkout lineage-21  # Adjust if necessary
          make vendor/obiwan_defconfig  # Use the specified device config

      - name: Build Kernel
        run: |
          cd android_kernel_asus_sm8250
          make -j$(nproc)

      - name: Build Device Tree Blob
        run: |
          cd android_kernel_asus_sm8250
          make dtbs

      - name: Archive Artifacts
        if: success()
        run: |
          mkdir -p $GITHUB_WORKSPACE/artifacts
          cp android_kernel_asus_sm8250/arch/arm64/boot/Image $GITHUB_WORKSPACE/artifacts/kernel.img
          cp android_kernel_asus_sm8250/arch/arm64/boot/dts/asus/sm8250-asus.dtb $GITHUB_WORKSPACE/artifacts/device_tree.dtb
          mkdir -p $GITHUB_WORKSPACE/artifacts/modules
          cp -r android_kernel_asus_sm8250/lib/modules/* $GITHUB_WORKSPACE/artifacts/modules/  # Include kernel modules
          mkdir -p $GITHUB_WORKSPACE/artifacts/dts
          cp -r android_kernel_asus_sm8250/arch/arm64/boot/dts/* $GITHUB_WORKSPACE/artifacts/dts/  # Include all DTS files
          echo "Kernel, device tree, and modules built successfully."

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3  # Updated to v3
        with:
          name: kernel-artifacts-${{ github.run_number }}  # Unique artifact name including run number
          path: artifacts/
