name: Modify boot.img

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  modify-boot-image:

    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install -y abootimg curl

    - name: Download boot.img
      run: |
        curl -L -o boot.img <URL_TO_BOOT_IMG>  # Replace with actual boot.img URL

    - name: Download kernel
      run: |
        curl -L -o new_kernel.img <URL_TO_NEW_KERNEL>  # Replace with actual kernel URL

    - name: Extract boot.img
      run: |
        mkdir bootimg
        abootimg --extract boot.img -o bootimg/

    - name: Replace kernel
      run: |
        cp new_kernel.img bootimg/zImage  # Adjust if the name of the kernel is different

    - name: Repack boot.img
      run: |
        abootimg --create new_boot.img -f bootimg/bootimg.cfg -k bootimg/zImage -r bootimg/rambase

    - name: Upload new boot.img
      uses: actions/upload-artifact@v2
      with:
        name: new_boot.img
        path: new_boot.img
