name: Unpack and Repack Boot Image

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  BOOT_IMG_PATH: "./boot.img"
  OUTPUT_DIR: "./output"
  REPACKED_IMG: "repacked-boot.img"

jobs:
  unpack_repack:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Download boot.img from SourceForge
    - name: Download boot.img from SourceForge
      run: |
        wget https://sourceforge.net/projects/payload/files/Boot/boot.img/download -O $BOOT_IMG_PATH
        echo "Downloaded boot.img from SourceForge"

    - name: Load Configurations
      env:
        CONFIG_FILE: config.env
      run: |
        if [ -f $CONFIG_FILE ]; then
          echo "Loading configurations from $CONFIG_FILE"
          set -a
          source $CONFIG_FILE
          set +a
        else
          echo "config.env file not found!"
          exit 1
        fi

    - name: Install Required Tools
      run: |
        sudo apt-get update
        sudo apt-get install -y abootimg

    - name: Unpack boot.img
      run: |
        mkdir -p $OUTPUT_DIR
        abootimg -x $BOOT_IMG_PATH -o $OUTPUT_DIR/bootimg.cfg

    - name: Check bootimg.cfg Content
      run: |
        echo "Contents of bootimg.cfg:"
        cat $OUTPUT_DIR/bootimg.cfg

    - name: Create a Valid bootimg.cfg
      run: |
        echo "Creating a valid bootimg.cfg file..."
        echo "kernel=./$KERNEL" > $OUTPUT_DIR/bootimg.cfg
        echo "ramdisk=./$RAMDISK" >> $OUTPUT_DIR/bootimg.cfg
        echo "cmdline=$CMDLINE" >> $OUTPUT_DIR/bootimg.cfg
        echo "pagesize=$PAGESIZE" >> $OUTPUT_DIR/bootimg.cfg
        echo "name=$BOOT_IMAGE_NAME" >> $OUTPUT_DIR/bootimg.cfg

    - name: Repack boot.img
      run: |
        abootimg --create $REPACKED_IMG -f $OUTPUT_DIR/bootimg.cfg -k $OUTPUT_DIR/$KERNEL -r $OUTPUT_DIR/$RAMDISK

    - name: Upload Repacked Boot Image
      uses: actions/upload-artifact@v3
      with:
        name: repacked-boot-img
        path: $REPACKED_IMG
